networks:
  journal:
    internal: true
  proxy:

services:
  journal:
    build: https://github.com/inoda/journal.git#main
    container_name: journal
    image: journal
    volumes:
      - /media/jc/floppy/journal/data:/app:rw
    environment:
      - RAILS_ENV=production
      - SITE_DOMAIN=192.168.68.69
      - DATABASE_URL=postgres://postgres:BvD55F79Usn3mAU@journal-db/placeholder
      - CIPHER_KEY=+hGIghzn52A665xnNbKvldQr2eGhgdI8wBHQzMRdwbQ= # openssl rand -base64 32
      - SHARING_TOKEN_CIPHER_IV=cVP7vGjQlAoaxmcxH9nTaQ== # openssl rand -base64 16
      - SECRET_KEY_BASE=8qP2pn8TNMZe4AwfS75y # random alphanumerical
    ports:
      - 3000:3000
    networks:
      - proxy
      - journal
    restart: unless-stopped

  journal-db:
    container_name: journal-postgres
    image: postgres:alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    environment:
      - POSTGRES_DB=placeholder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=BvD55F79Usn3mAU
    volumes:
      - /media/jc/floppy/journal/postgres:/var/lib/postgresql/data:rw
    networks:
      - journal
    restart: unless-stopped
